### ISSUE TITLE
Folders in static location (from /src/main/static) are not represented as folders in S3 bucket

### ISSUE THREAD

**Issue by v79** [cjkent/osiris#509] opened 2020-04-30 20:21 UTC
Hi,

I've noticed that when my static folder location /src/main/static contains sub-folders, these are not uploaded as 'folders' in S3.

For instance, `src/main/static/css/css.ss` is given an S3 URL of:

`https://<<bucketname>>.s3.eu-west-2.amazonaws.com/<<random>>/css%5Ccss.css`

Whereas I'd expect it to be:

`https://<<bucketname>>.s3.eu-west-2.amazonaws.com/<<random>>/css/css.css`

So naturally my CSS is not loading :). It appears the folder separator is being URL-encoded on upload.

Deploying from Windows 10, gradle 6.3, kotlin 1.3.31.

**Comment by cjkent** [comment] 2020-04-30 21:36
That looks like it's specific to Windows, I can't reproduce it on macOS. How sloppy of me :(

Sorry about that, I hope it should be an easy fix.

**Comment by v79** [comment] 2020-05-01 05:21
Thank you. I'll stick to a flat file structure for now, but I will want to have folders eventually.
Ironically, the other Kotlin serverless framework I've tried (Kotless) also fails on Windows, and I had to use Windows Subsystem for Linux to get it to deploy at all.
Osiris has got me up-and-running much more effectively!

**Comment by cjkent** [comment] 2020-05-01 09:51
This _should_ be fixed in 1.5.1 which I've just released (it might not appear in Maven central for up to an hour).

I can't test under Windows, so please let me know if it works.

**Closed** 2020-05-01 10:08 UTC

**Comment by v79** [comment] 2020-05-01 14:32
Yes, it's working fine with 1.5.1. Thanks for the quick response.
